package aI40minontology;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: DiscreteDynamicsModel <br>
 * @version generated on Sun Feb 10 20:58:15 COT 2019 by Santiago
 */

public interface DiscreteDynamicsModel extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasModelElement
     */
     
    /**
     * Gets all property values for the hasModelElement property.<p>
     * 
     * @returns a collection of values for the hasModelElement property.
     */
    Collection<? extends ModelElement> getHasModelElement();

    /**
     * Checks if the class has a hasModelElement property value.<p>
     * 
     * @return true if there is a hasModelElement property value.
     */
    boolean hasHasModelElement();

    /**
     * Adds a hasModelElement property value.<p>
     * 
     * @param newHasModelElement the hasModelElement property value to be added
     */
    void addHasModelElement(ModelElement newHasModelElement);

    /**
     * Removes a hasModelElement property value.<p>
     * 
     * @param oldHasModelElement the hasModelElement property value to be removed.
     */
    void removeHasModelElement(ModelElement oldHasModelElement);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
