package aI40minontology;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Domain <br>
 * @version generated on Sun Feb 10 20:58:15 COT 2019 by Santiago
 */

public interface Domain extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/Automation-I4.0-Ontology#establishes
     */
     
    /**
     * Gets all property values for the establishes property.<p>
     * 
     * @returns a collection of values for the establishes property.
     */
    Collection<? extends Semantics> getEstablishes();

    /**
     * Checks if the class has a establishes property value.<p>
     * 
     * @return true if there is a establishes property value.
     */
    boolean hasEstablishes();

    /**
     * Adds a establishes property value.<p>
     * 
     * @param newEstablishes the establishes property value to be added
     */
    void addEstablishes(Semantics newEstablishes);

    /**
     * Removes a establishes property value.<p>
     * 
     * @param oldEstablishes the establishes property value to be removed.
     */
    void removeEstablishes(Semantics oldEstablishes);


    /* ***************************************************
     * Property http://www.semanticweb.org/Automation-I4.0-Ontology#isNormalizedBy
     */
     
    /**
     * Gets all property values for the isNormalizedBy property.<p>
     * 
     * @returns a collection of values for the isNormalizedBy property.
     */
    Collection<? extends Standard> getIsNormalizedBy();

    /**
     * Checks if the class has a isNormalizedBy property value.<p>
     * 
     * @return true if there is a isNormalizedBy property value.
     */
    boolean hasIsNormalizedBy();

    /**
     * Adds a isNormalizedBy property value.<p>
     * 
     * @param newIsNormalizedBy the isNormalizedBy property value to be added
     */
    void addIsNormalizedBy(Standard newIsNormalizedBy);

    /**
     * Removes a isNormalizedBy property value.<p>
     * 
     * @param oldIsNormalizedBy the isNormalizedBy property value to be removed.
     */
    void removeIsNormalizedBy(Standard oldIsNormalizedBy);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
