package aI40minontology;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Representation <br>
 * @version generated on Sun Feb 10 20:58:15 COT 2019 by Santiago
 */

public interface Representation extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/Automation-I4.0-Ontology#defines
     */
     
    /**
     * Gets all property values for the defines property.<p>
     * 
     * @returns a collection of values for the defines property.
     */
    Collection<? extends WrappedIndividual> getDefines();

    /**
     * Checks if the class has a defines property value.<p>
     * 
     * @return true if there is a defines property value.
     */
    boolean hasDefines();

    /**
     * Adds a defines property value.<p>
     * 
     * @param newDefines the defines property value to be added
     */
    void addDefines(WrappedIndividual newDefines);

    /**
     * Removes a defines property value.<p>
     * 
     * @param oldDefines the defines property value to be removed.
     */
    void removeDefines(WrappedIndividual oldDefines);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
