package aI40minontology;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Architecture <br>
 * @version generated on Sun Feb 10 20:58:15 COT 2019 by Santiago
 */

public interface Architecture extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/Automation-I4.0-Ontology#isComposedBy
     */
     
    /**
     * Gets all property values for the isComposedBy property.<p>
     * 
     * @returns a collection of values for the isComposedBy property.
     */
    Collection<? extends Actor> getIsComposedBy();

    /**
     * Checks if the class has a isComposedBy property value.<p>
     * 
     * @return true if there is a isComposedBy property value.
     */
    boolean hasIsComposedBy();

    /**
     * Adds a isComposedBy property value.<p>
     * 
     * @param newIsComposedBy the isComposedBy property value to be added
     */
    void addIsComposedBy(Actor newIsComposedBy);

    /**
     * Removes a isComposedBy property value.<p>
     * 
     * @param oldIsComposedBy the isComposedBy property value to be removed.
     */
    void removeIsComposedBy(Actor oldIsComposedBy);


    /* ***************************************************
     * Property http://www.semanticweb.org/Automation-I4.0-Ontology#isImplementedBy
     */
     
    /**
     * Gets all property values for the isImplementedBy property.<p>
     * 
     * @returns a collection of values for the isImplementedBy property.
     */
    Collection<? extends Network> getIsImplementedBy();

    /**
     * Checks if the class has a isImplementedBy property value.<p>
     * 
     * @return true if there is a isImplementedBy property value.
     */
    boolean hasIsImplementedBy();

    /**
     * Adds a isImplementedBy property value.<p>
     * 
     * @param newIsImplementedBy the isImplementedBy property value to be added
     */
    void addIsImplementedBy(Network newIsImplementedBy);

    /**
     * Removes a isImplementedBy property value.<p>
     * 
     * @param oldIsImplementedBy the isImplementedBy property value to be removed.
     */
    void removeIsImplementedBy(Network oldIsImplementedBy);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
