package aI40minontology;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Language <br>
 * @version generated on Sun Feb 10 20:58:15 COT 2019 by Santiago
 */

public interface Language extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/Automation-I4.0-Ontology#compliesSemanticInteroperability
     */
     
    /**
     * Gets all property values for the compliesSemanticInteroperability property.<p>
     * 
     * @returns a collection of values for the compliesSemanticInteroperability property.
     */
    Collection<? extends SemanticInteroperability> getCompliesSemanticInteroperability();

    /**
     * Checks if the class has a compliesSemanticInteroperability property value.<p>
     * 
     * @return true if there is a compliesSemanticInteroperability property value.
     */
    boolean hasCompliesSemanticInteroperability();

    /**
     * Adds a compliesSemanticInteroperability property value.<p>
     * 
     * @param newCompliesSemanticInteroperability the compliesSemanticInteroperability property value to be added
     */
    void addCompliesSemanticInteroperability(SemanticInteroperability newCompliesSemanticInteroperability);

    /**
     * Removes a compliesSemanticInteroperability property value.<p>
     * 
     * @param oldCompliesSemanticInteroperability the compliesSemanticInteroperability property value to be removed.
     */
    void removeCompliesSemanticInteroperability(SemanticInteroperability oldCompliesSemanticInteroperability);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
