package aI40minontology;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Sun Feb 10 20:58:15 COT 2019 by Santiago
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Actor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ACTOR.<p>
     * 
     */
    public static final OWLClass CLASS_ACTOR = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Actor"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#AdvancedFunction
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ADVANCEDFUNCTION.<p>
     * 
     */
    public static final OWLClass CLASS_ADVANCEDFUNCTION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#AdvancedFunction"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#AnalogInput
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ANALOGINPUT.<p>
     * 
     */
    public static final OWLClass CLASS_ANALOGINPUT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#AnalogInput"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#AnalogOutput
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ANALOGOUTPUT.<p>
     * 
     */
    public static final OWLClass CLASS_ANALOGOUTPUT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#AnalogOutput"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#AnalogVariable
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ANALOGVARIABLE.<p>
     * 
     */
    public static final OWLClass CLASS_ANALOGVARIABLE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#AnalogVariable"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Arc
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ARC.<p>
     * 
     */
    public static final OWLClass CLASS_ARC = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Arc"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Architecture
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ARCHITECTURE.<p>
     * 
     */
    public static final OWLClass CLASS_ARCHITECTURE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Architecture"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#As-a-ServiceFunction
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AS_A_SERVICEFUNCTION.<p>
     * 
     */
    public static final OWLClass CLASS_AS_A_SERVICEFUNCTION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#As-a-ServiceFunction"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#BidirectionalArc
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BIDIRECTIONALARC.<p>
     * 
     */
    public static final OWLClass CLASS_BIDIRECTIONALARC = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#BidirectionalArc"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#ConcurrentState
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONCURRENTSTATE.<p>
     * 
     */
    public static final OWLClass CLASS_CONCURRENTSTATE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#ConcurrentState"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#CurrentState
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURRENTSTATE.<p>
     * 
     */
    public static final OWLClass CLASS_CURRENTSTATE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#CurrentState"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#DataInput
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DATAINPUT.<p>
     * 
     */
    public static final OWLClass CLASS_DATAINPUT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#DataInput"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#DataOutput
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DATAOUTPUT.<p>
     * 
     */
    public static final OWLClass CLASS_DATAOUTPUT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#DataOutput"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#DataStream
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DATASTREAM.<p>
     * 
     */
    public static final OWLClass CLASS_DATASTREAM = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#DataStream"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#DataVariable
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DATAVARIABLE.<p>
     * 
     */
    public static final OWLClass CLASS_DATAVARIABLE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#DataVariable"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Device
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEVICE.<p>
     * 
     */
    public static final OWLClass CLASS_DEVICE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Device"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#DigitalInput
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DIGITALINPUT.<p>
     * 
     */
    public static final OWLClass CLASS_DIGITALINPUT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#DigitalInput"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#DigitalOutput
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DIGITALOUTPUT.<p>
     * 
     */
    public static final OWLClass CLASS_DIGITALOUTPUT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#DigitalOutput"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#DigitalVariable
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DIGITALVARIABLE.<p>
     * 
     */
    public static final OWLClass CLASS_DIGITALVARIABLE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#DigitalVariable"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#DiscreteDynamicsModel
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DISCRETEDYNAMICSMODEL.<p>
     * 
     */
    public static final OWLClass CLASS_DISCRETEDYNAMICSMODEL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#DiscreteDynamicsModel"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Domain
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DOMAIN.<p>
     * 
     */
    public static final OWLClass CLASS_DOMAIN = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Domain"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Entity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ENTITY.<p>
     * 
     */
    public static final OWLClass CLASS_ENTITY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Entity"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#FinalState
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FINALSTATE.<p>
     * 
     */
    public static final OWLClass CLASS_FINALSTATE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#FinalState"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Function
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FUNCTION.<p>
     * 
     */
    public static final OWLClass CLASS_FUNCTION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Function"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Information
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_INFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Information"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#InitialState
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INITIALSTATE.<p>
     * 
     */
    public static final OWLClass CLASS_INITIALSTATE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#InitialState"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Input
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INPUT.<p>
     * 
     */
    public static final OWLClass CLASS_INPUT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Input"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Interoperability
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INTEROPERABILITY.<p>
     * 
     */
    public static final OWLClass CLASS_INTEROPERABILITY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Interoperability"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Language
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LANGUAGE.<p>
     * 
     */
    public static final OWLClass CLASS_LANGUAGE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Language"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Loop
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LOOP.<p>
     * 
     */
    public static final OWLClass CLASS_LOOP = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Loop"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#ManyToManyTransition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MANYTOMANYTRANSITION.<p>
     * 
     */
    public static final OWLClass CLASS_MANYTOMANYTRANSITION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#ManyToManyTransition"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#ManyToOneTransition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MANYTOONETRANSITION.<p>
     * 
     */
    public static final OWLClass CLASS_MANYTOONETRANSITION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#ManyToOneTransition"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#ModelElement
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MODELELEMENT.<p>
     * 
     */
    public static final OWLClass CLASS_MODELELEMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#ModelElement"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#MultivariableStateFunction
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MULTIVARIABLESTATEFUNCTION.<p>
     * 
     */
    public static final OWLClass CLASS_MULTIVARIABLESTATEFUNCTION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#MultivariableStateFunction"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#MultivariableTransitionFunction
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MULTIVARIABLETRANSITIONFUNCTION.<p>
     * 
     */
    public static final OWLClass CLASS_MULTIVARIABLETRANSITIONFUNCTION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#MultivariableTransitionFunction"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Network
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NETWORK.<p>
     * 
     */
    public static final OWLClass CLASS_NETWORK = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Network"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#NextState
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NEXTSTATE.<p>
     * 
     */
    public static final OWLClass CLASS_NEXTSTATE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#NextState"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#OneToManyTransition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ONETOMANYTRANSITION.<p>
     * 
     */
    public static final OWLClass CLASS_ONETOMANYTRANSITION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#OneToManyTransition"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#OneToOneTransition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ONETOONETRANSITION.<p>
     * 
     */
    public static final OWLClass CLASS_ONETOONETRANSITION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#OneToOneTransition"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Output
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OUTPUT.<p>
     * 
     */
    public static final OWLClass CLASS_OUTPUT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Output"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Person
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSON.<p>
     * 
     */
    public static final OWLClass CLASS_PERSON = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Person"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#PreviousState
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PREVIOUSSTATE.<p>
     * 
     */
    public static final OWLClass CLASS_PREVIOUSSTATE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#PreviousState"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Process_
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROCESS_.<p>
     * 
     */
    public static final OWLClass CLASS_PROCESS_ = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Process_"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Product-Asset
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRODUCT_ASSET.<p>
     * 
     */
    public static final OWLClass CLASS_PRODUCT_ASSET = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Product-Asset"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Protocol
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROTOCOL.<p>
     * 
     */
    public static final OWLClass CLASS_PROTOCOL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Protocol"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Representation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REPRESENTATION.<p>
     * 
     */
    public static final OWLClass CLASS_REPRESENTATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Representation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#RequestFunction
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REQUESTFUNCTION.<p>
     * 
     */
    public static final OWLClass CLASS_REQUESTFUNCTION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#RequestFunction"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Resource
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESOURCE.<p>
     * 
     */
    public static final OWLClass CLASS_RESOURCE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Resource"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Resource-SharedState
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESOURCE_SHAREDSTATE.<p>
     * 
     */
    public static final OWLClass CLASS_RESOURCE_SHAREDSTATE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Resource-SharedState"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#SemanticInteroperability
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SEMANTICINTEROPERABILITY.<p>
     * 
     */
    public static final OWLClass CLASS_SEMANTICINTEROPERABILITY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#SemanticInteroperability"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Semantics
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SEMANTICS.<p>
     * 
     */
    public static final OWLClass CLASS_SEMANTICS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Semantics"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Sequence
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SEQUENCE.<p>
     * 
     */
    public static final OWLClass CLASS_SEQUENCE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Sequence"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Service
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SERVICE.<p>
     * 
     */
    public static final OWLClass CLASS_SERVICE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Service"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#SetElement
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SETELEMENT.<p>
     * 
     */
    public static final OWLClass CLASS_SETELEMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#SetElement"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#SoftwareResource
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SOFTWARERESOURCE.<p>
     * 
     */
    public static final OWLClass CLASS_SOFTWARERESOURCE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#SoftwareResource"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Standard
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class STANDARD.<p>
     * 
     */
    public static final OWLClass CLASS_STANDARD = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Standard"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#State
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class STATE.<p>
     * 
     */
    public static final OWLClass CLASS_STATE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#State"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#StateFunction
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class STATEFUNCTION.<p>
     * 
     */
    public static final OWLClass CLASS_STATEFUNCTION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#StateFunction"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Subloop
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SUBLOOP.<p>
     * 
     */
    public static final OWLClass CLASS_SUBLOOP = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Subloop"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Subsequence
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SUBSEQUENCE.<p>
     * 
     */
    public static final OWLClass CLASS_SUBSEQUENCE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Subsequence"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#SynchronousState
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SYNCHRONOUSSTATE.<p>
     * 
     */
    public static final OWLClass CLASS_SYNCHRONOUSSTATE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#SynchronousState"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#SyntacticInteroperability
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SYNTACTICINTEROPERABILITY.<p>
     * 
     */
    public static final OWLClass CLASS_SYNTACTICINTEROPERABILITY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#SyntacticInteroperability"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Thing
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class THING.<p>
     * 
     */
    public static final OWLClass CLASS_THING = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Thing"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Transition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TRANSITION.<p>
     * 
     */
    public static final OWLClass CLASS_TRANSITION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Transition"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#TransitionFunction
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TRANSITIONFUNCTION.<p>
     * 
     */
    public static final OWLClass CLASS_TRANSITIONFUNCTION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#TransitionFunction"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#UnidirectionalArc
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class UNIDIRECTIONALARC.<p>
     * 
     */
    public static final OWLClass CLASS_UNIDIRECTIONALARC = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#UnidirectionalArc"));

    /* ***************************************************
     * Class http://www.semanticweb.org/Automation-I4.0-Ontology#Variable
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VARIABLE.<p>
     * 
     */
    public static final OWLClass CLASS_VARIABLE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#Variable"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#actsOver
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ACTSOVER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ACTSOVER = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#actsOver"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#belongsToSequence
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property BELONGSTOSEQUENCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_BELONGSTOSEQUENCE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#belongsToSequence"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#belongsToSubsequence
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property BELONGSTOSUBSEQUENCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_BELONGSTOSUBSEQUENCE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#belongsToSubsequence"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#callsAService
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CALLSASERVICE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CALLSASERVICE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#callsAService"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#compliesSemanticInteroperability
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property COMPLIESSEMANTICINTEROPERABILITY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COMPLIESSEMANTICINTEROPERABILITY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#compliesSemanticInteroperability"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#compliesSyntacticInteroperability
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property COMPLIESSYNTACTICINTEROPERABILITY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COMPLIESSYNTACTICINTEROPERABILITY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#compliesSyntacticInteroperability"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#contains
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTAINS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTAINS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#contains"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#defines
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DEFINES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DEFINES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#defines"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#ensures
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ENSURES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ENSURES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#ensures"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#establishes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ESTABLISHES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ESTABLISHES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#establishes"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#executes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EXECUTES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EXECUTES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#executes"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#executesAServiceFunction
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EXECUTESASERVICEFUNCTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EXECUTESASERVICEFUNCTION = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#executesAServiceFunction"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#finalizesLoop
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FINALIZESLOOP.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FINALIZESLOOP = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#finalizesLoop"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#finalizesSequence
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FINALIZESSEQUENCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FINALIZESSEQUENCE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#finalizesSequence"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#finalizesSubsequence
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FINALIZESSUBSEQUENCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FINALIZESSUBSEQUENCE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#finalizesSubsequence"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#formalizes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FORMALIZES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FORMALIZES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#formalizes"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#generates
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property GENERATES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_GENERATES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#generates"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasAssociatedModel
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASASSOCIATEDMODEL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASASSOCIATEDMODEL = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasAssociatedModel"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasDomain
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASDOMAIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASDOMAIN = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasDomain"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasModelElement
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASMODELELEMENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASMODELELEMENT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasModelElement"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasNextState
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASNEXTSTATE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASNEXTSTATE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasNextState"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasPreviousState
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASPREVIOUSSTATE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASPREVIOUSSTATE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasPreviousState"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasResource
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASRESOURCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASRESOURCE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasResource"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasSinkPoint
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSINKPOINT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSINKPOINT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasSinkPoint"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasSourcePoint
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSOURCEPOINT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSOURCEPOINT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasSourcePoint"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasStateFunction
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSTATEFUNCTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSTATEFUNCTION = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasStateFunction"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasTransitionFunction
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASTRANSITIONFUNCTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASTRANSITIONFUNCTION = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasTransitionFunction"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#initializesLoop
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INITIALIZESLOOP.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INITIALIZESLOOP = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#initializesLoop"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#initializesSequence
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INITIALIZESSEQUENCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INITIALIZESSEQUENCE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#initializesSequence"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#initializesSubsequence
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INITIALIZESSUBSEQUENCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INITIALIZESSUBSEQUENCE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#initializesSubsequence"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#interacts
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INTERACTS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INTERACTS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#interacts"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#isComposedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCOMPOSEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCOMPOSEDBY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#isComposedBy"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#isConnectedToArc
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONNECTEDTOARC.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONNECTEDTOARC = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#isConnectedToArc"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#isConnectedToState
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONNECTEDTOSTATE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONNECTEDTOSTATE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#isConnectedToState"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#isConnectedToTransition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONNECTEDTOTRANSITION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONNECTEDTOTRANSITION = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#isConnectedToTransition"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#isContextVariableOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONTEXTVARIABLEOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONTEXTVARIABLEOF = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#isContextVariableOf"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#isExecutedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISEXECUTEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISEXECUTEDBY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#isExecutedBy"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#isImplementedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISIMPLEMENTEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISIMPLEMENTEDBY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#isImplementedBy"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#isNormalizedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISNORMALIZEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISNORMALIZEDBY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#isNormalizedBy"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#isPerformedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPERFORMEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPERFORMEDBY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#isPerformedBy"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#offers
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OFFERS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OFFERS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#offers"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#providesInformationToState
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PROVIDESINFORMATIONTOSTATE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PROVIDESINFORMATIONTOSTATE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#providesInformationToState"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#readsAbout
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property READSABOUT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_READSABOUT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#readsAbout"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#receives
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property RECEIVES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_RECEIVES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#receives"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#receivesDataStream
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property RECEIVESDATASTREAM.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_RECEIVESDATASTREAM = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#receivesDataStream"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#receivesParameter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property RECEIVESPARAMETER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_RECEIVESPARAMETER = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#receivesParameter"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#requires
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REQUIRES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REQUIRES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#requires"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#returnsResult
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property RETURNSRESULT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_RETURNSRESULT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#returnsResult"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#runsAService
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property RUNSASERVICE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_RUNSASERVICE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#runsAService"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#spreads
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SPREADS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SPREADS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#spreads"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#standardizes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property STANDARDIZES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_STANDARDIZES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#standardizes"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#transmits
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TRANSMITS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TRANSMITS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#transmits"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#understands
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property UNDERSTANDS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_UNDERSTANDS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#understands"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#topObjectProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:TOPOBJECTPROPERTY.<p>
     * 
     */
    //public static final OWLObjectProperty OBJECT_PROPERTY_OWL:TOPOBJECTPROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#topObjectProperty"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#belongsToArchitectureLevel
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property BELONGSTOARCHITECTURELEVEL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_BELONGSTOARCHITECTURELEVEL = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#belongsToArchitectureLevel"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#concernsTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CONCERNSTO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CONCERNSTO = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#concernsTo"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasCharacteristic
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCHARACTERISTIC.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCHARACTERISTIC = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasCharacteristic"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasContent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCONTENT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCONTENT = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasContent"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasDBpediaResource
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDBPEDIARESOURCE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDBPEDIARESOURCE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasDBpediaResource"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasDataType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDATATYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDATATYPE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasDataType"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasDescription
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDESCRIPTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDESCRIPTION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasDescription"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasEmbeddingCapability
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASEMBEDDINGCAPABILITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASEMBEDDINGCAPABILITY = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasEmbeddingCapability"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasIdentifier
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASIDENTIFIER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASIDENTIFIER = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasIdentifier"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasInteroperabilityDegree
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASINTEROPERABILITYDEGREE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASINTEROPERABILITYDEGREE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasInteroperabilityDegree"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasNumberOfAssignment
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASNUMBEROFASSIGNMENT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASNUMBEROFASSIGNMENT = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasNumberOfAssignment"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasNumberOfParameters
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASNUMBEROFPARAMETERS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASNUMBEROFPARAMETERS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasNumberOfParameters"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasNumberOfStates
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASNUMBEROFSTATES.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASNUMBEROFSTATES = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasNumberOfStates"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasNumberOfTasks
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASNUMBEROFTASKS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASNUMBEROFTASKS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasNumberOfTasks"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasNumberOfTransitions
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASNUMBEROFTRANSITIONS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASNUMBEROFTRANSITIONS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasNumberOfTransitions"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasOfficialResource
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASOFFICIALRESOURCE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASOFFICIALRESOURCE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasOfficialResource"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasReceiver
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASRECEIVER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASRECEIVER = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasReceiver"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasReturnDataType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASRETURNDATATYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASRETURNDATATYPE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasReturnDataType"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasReturnValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASRETURNVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASRETURNVALUE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasReturnValue"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasSoftwareContent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSOFTWARECONTENT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSOFTWARECONTENT = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasSoftwareContent"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasTransmitter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASTRANSMITTER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASTRANSMITTER = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasTransmitter"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#hasValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASVALUE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#hasValue"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#isActive
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ISACTIVE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ISACTIVE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#isActive"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#isChildSetElement
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ISCHILDSETELEMENT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ISCHILDSETELEMENT = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#isChildSetElement"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#isContextStandard
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ISCONTEXTSTANDARD.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ISCONTEXTSTANDARD = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#isContextStandard"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#isEnabled
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ISENABLED.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ISENABLED = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#isEnabled"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/Automation-I4.0-Ontology#isParentSetElement
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ISPARENTSETELEMENT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ISPARENTSETELEMENT = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/Automation-I4.0-Ontology#isParentSetElement"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#topDataProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property OWL:TOPDATAPROPERTY.<p>
     * 
     */
    //public static final OWLDataProperty DATA_PROPERTY_OWL:TOPDATAPROPERTY = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#topDataProperty"));


}
