package aI40ontology;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: DynamicsModel <br>
 * @version generated on Mon Feb 22 13:42:44 COT 2021 by sagga
 */

public interface DynamicsModel extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/santiago/Automation-I4.0-Ontology#defines
     */
     
    /**
     * Gets all property values for the defines property.<p>
     * 
     * @returns a collection of values for the defines property.
     */
    Collection<? extends Architecture> getDefines();

    /**
     * Checks if the class has a defines property value.<p>
     * 
     * @return true if there is a defines property value.
     */
    boolean hasDefines();

    /**
     * Adds a defines property value.<p>
     * 
     * @param newDefines the defines property value to be added
     */
    void addDefines(Architecture newDefines);

    /**
     * Removes a defines property value.<p>
     * 
     * @param oldDefines the defines property value to be removed.
     */
    void removeDefines(Architecture oldDefines);


    /* ***************************************************
     * Property http://www.semanticweb.org/santiago/Automation-I4.0-Ontology#hasModelElement
     */
     
    /**
     * Gets all property values for the hasModelElement property.<p>
     * 
     * @returns a collection of values for the hasModelElement property.
     */
    Collection<? extends ModelElement> getHasModelElement();

    /**
     * Checks if the class has a hasModelElement property value.<p>
     * 
     * @return true if there is a hasModelElement property value.
     */
    boolean hasHasModelElement();

    /**
     * Adds a hasModelElement property value.<p>
     * 
     * @param newHasModelElement the hasModelElement property value to be added
     */
    void addHasModelElement(ModelElement newHasModelElement);

    /**
     * Removes a hasModelElement property value.<p>
     * 
     * @param oldHasModelElement the hasModelElement property value to be removed.
     */
    void removeHasModelElement(ModelElement oldHasModelElement);


    /* ***************************************************
     * Property http://www.semanticweb.org/santiago/Automation-I4.0-Ontology#hasConstraint
     */
     
    /**
     * Gets all property values for the hasConstraint property.<p>
     * 
     * @returns a collection of values for the hasConstraint property.
     */
    Collection<? extends String> getHasConstraint();

    /**
     * Checks if the class has a hasConstraint property value.<p>
     * 
     * @return true if there is a hasConstraint property value.
     */
    boolean hasHasConstraint();

    /**
     * Adds a hasConstraint property value.<p>
     * 
     * @param newHasConstraint the hasConstraint property value to be added
     */
    void addHasConstraint(String newHasConstraint);

    /**
     * Removes a hasConstraint property value.<p>
     * 
     * @param oldHasConstraint the hasConstraint property value to be removed.
     */
    void removeHasConstraint(String oldHasConstraint);



    /* ***************************************************
     * Property http://www.semanticweb.org/santiago/Automation-I4.0-Ontology#hasDescription
     */
     
    /**
     * Gets all property values for the hasDescription property.<p>
     * 
     * @returns a collection of values for the hasDescription property.
     */
    Collection<? extends String> getHasDescription();

    /**
     * Checks if the class has a hasDescription property value.<p>
     * 
     * @return true if there is a hasDescription property value.
     */
    boolean hasHasDescription();

    /**
     * Adds a hasDescription property value.<p>
     * 
     * @param newHasDescription the hasDescription property value to be added
     */
    void addHasDescription(String newHasDescription);

    /**
     * Removes a hasDescription property value.<p>
     * 
     * @param oldHasDescription the hasDescription property value to be removed.
     */
    void removeHasDescription(String oldHasDescription);



    /* ***************************************************
     * Property http://www.semanticweb.org/santiago/Automation-I4.0-Ontology#hasRelatedOntology
     */
     
    /**
     * Gets all property values for the hasRelatedOntology property.<p>
     * 
     * @returns a collection of values for the hasRelatedOntology property.
     */
    Collection<? extends Object> getHasRelatedOntology();

    /**
     * Checks if the class has a hasRelatedOntology property value.<p>
     * 
     * @return true if there is a hasRelatedOntology property value.
     */
    boolean hasHasRelatedOntology();

    /**
     * Adds a hasRelatedOntology property value.<p>
     * 
     * @param newHasRelatedOntology the hasRelatedOntology property value to be added
     */
    void addHasRelatedOntology(Object newHasRelatedOntology);

    /**
     * Removes a hasRelatedOntology property value.<p>
     * 
     * @param oldHasRelatedOntology the hasRelatedOntology property value to be removed.
     */
    void removeHasRelatedOntology(Object oldHasRelatedOntology);



    /* ***************************************************
     * Property http://www.semanticweb.org/santiago/Automation-I4.0-Ontology#hasRequirement
     */
     
    /**
     * Gets all property values for the hasRequirement property.<p>
     * 
     * @returns a collection of values for the hasRequirement property.
     */
    Collection<? extends String> getHasRequirement();

    /**
     * Checks if the class has a hasRequirement property value.<p>
     * 
     * @return true if there is a hasRequirement property value.
     */
    boolean hasHasRequirement();

    /**
     * Adds a hasRequirement property value.<p>
     * 
     * @param newHasRequirement the hasRequirement property value to be added
     */
    void addHasRequirement(String newHasRequirement);

    /**
     * Removes a hasRequirement property value.<p>
     * 
     * @param oldHasRequirement the hasRequirement property value to be removed.
     */
    void removeHasRequirement(String oldHasRequirement);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
