package aI40minontology.impl;

import aI40minontology.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultLanguage <br>
 * @version generated on Sun Feb 10 20:58:15 COT 2019 by Santiago
 */
public class DefaultLanguage extends WrappedIndividualImpl implements Language {

    public DefaultLanguage(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.semanticweb.org/Automation-I4.0-Ontology#compliesSemanticInteroperability
     */
     
    public Collection<? extends SemanticInteroperability> getCompliesSemanticInteroperability() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_COMPLIESSEMANTICINTEROPERABILITY,
                                               DefaultSemanticInteroperability.class);
    }

    public boolean hasCompliesSemanticInteroperability() {
	   return !getCompliesSemanticInteroperability().isEmpty();
    }

    public void addCompliesSemanticInteroperability(SemanticInteroperability newCompliesSemanticInteroperability) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_COMPLIESSEMANTICINTEROPERABILITY,
                                       newCompliesSemanticInteroperability);
    }

    public void removeCompliesSemanticInteroperability(SemanticInteroperability oldCompliesSemanticInteroperability) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_COMPLIESSEMANTICINTEROPERABILITY,
                                          oldCompliesSemanticInteroperability);
    }


}
